# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuckNorris' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuckNorris

	pod 'Moya', '~> 15.0'

  target 'ChuckNorrisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChuckNorrisUITests' do
    # Pods for testing
  end

end
